import type { Metadata } from "next";
import React from "react";
import "@repo/design-system/styles/globals.css";

export const metadata: Metadata = {
	title: "NextNova - Admin",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: React.ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => {
	return (
		<html lang="en">
			<body className="antialiased">{children}</body>
		</html>
	);
};

export default RootLayout;
